// Generated by CoffeeScript 1.10.0
(function() {
  var Parser, PugInheritance, fs, pkginfo;

  Parser = require('./parser');

  fs = require('fs');

  pkginfo = JSON.parse(fs.readFileSync('./package.json', 'utf8'));

  PugInheritance = (function() {
    function PugInheritance(filename, directory, options) {
      var parser;
      parser = new Parser(filename, directory, options);
      this.tree = parser.tree;
      this.files = parser.files;
      return this;
    }

    return PugInheritance;

  })();

  module.exports = PugInheritance;

}).call(this);
